server:
  port: 80
  servlet:
    session:
      timeout: 7200 # session超时时间

spring:
  profiles:
    active: @profileActive@

  session:
    store-type: redis
    timeout: 2h
    redis:
      namespace: session




